Do not poll counters in bulk mode during initialization for objects that support bulk per CLI option
stephenxs/sonic-sairedis pull request #16
Opened 2024-09-30 09:27 UTC by stephenxs

Do not poll counters in bulk mode during initialization for objects that support bulk per CLI option

2024-10-01 08:57 UTC, DavidZagury requested changes
Fix missing function

2024-10-01 08:57 UTC, DavidZagury commented on syncd/FlexCounter.cpp
> +                    getCounterContext(counterTypeRef->second)->setNoDoubleCheckBulkCapability(true);
@stephenxs the function setNoDoubleCheckBulkCapability does not exists

2024-10-15 06:01 UTC, stephenxs commented
ci 4481 + rerun 587 passed

2024-10-18 09:31 UTC, keboliu approved these changes

2024-10-19 00:28 UTC, stephenxs commented
ci 4519 passed

2024-10-20 13:59 UTC, closed without merging

2024-10-20 13:59 UTC, stephenxs commented
Force push to squash and avoid conflict.